// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeCEKDM1ynBpS6Ajai8pIeowsqzmfIDZQ',
    appId: '1:416120797073:web:762f2bfa485c8f52048c30',
    messagingSenderId: '416120797073',
    projectId: 'languages-study-9d484',
    authDomain: 'languages-study-9d484.firebaseapp.com',
    databaseURL: 'https://languages-study-9d484-default-rtdb.firebaseio.com',
    storageBucket: 'languages-study-9d484.appspot.com',
    measurementId: 'G-YXM5GP59WZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC487f9HV6B64iL9mlxtaynSKE66sZt-og',
    appId: '1:416120797073:android:72bced03eb29c3d0048c30',
    messagingSenderId: '416120797073',
    projectId: 'languages-study-9d484',
    databaseURL: 'https://languages-study-9d484-default-rtdb.firebaseio.com',
    storageBucket: 'languages-study-9d484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMOzVWzpqYvz6WJ2bP1C92eMXnViSgiCI',
    appId: '1:416120797073:ios:218bf1f190310e4e048c30',
    messagingSenderId: '416120797073',
    projectId: 'languages-study-9d484',
    databaseURL: 'https://languages-study-9d484-default-rtdb.firebaseio.com',
    storageBucket: 'languages-study-9d484.appspot.com',
    iosClientId: '416120797073-5k7h3u4c4d6oplls6v4dtdkjap5btjcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.languageStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMOzVWzpqYvz6WJ2bP1C92eMXnViSgiCI',
    appId: '1:416120797073:ios:218bf1f190310e4e048c30',
    messagingSenderId: '416120797073',
    projectId: 'languages-study-9d484',
    databaseURL: 'https://languages-study-9d484-default-rtdb.firebaseio.com',
    storageBucket: 'languages-study-9d484.appspot.com',
    iosClientId: '416120797073-5k7h3u4c4d6oplls6v4dtdkjap5btjcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.languageStudy',
  );
}
